##########
# Script: generate_changelog_bug_slides.py
# Description: Generate PowerPoint slides summarizing bug tickets from the
#              newest changelog release (HostSoftware 12.1.2.0.3 + BMC 12.1.2.0.2
#              + FwUpdate 12.1.2.0.1 + JKR 12.1.2.0.2 + MYR 12.1.2.0.1).
# Author: John Macdonald (generated by OpenCode)
##########
'''
Generates changelog_bug_tickets_12_1_2.pptx with 5 slides:
  Slide 1: Overview -- summary table of 30 bug tickets by category
  Slide 2: Driver Bugs (18 tickets)
  Slide 3: BMCFW Bugs (3 tickets)
  Slide 4: HFIFW Bug (1 ticket)
  Slide 5: Libfabric Bugs (8 tickets)

All STL-XXXXX ticket IDs are clickable Jira hyperlinks.

Usage:
    python generate_changelog_bug_slides.py

Output:
    changelog_bug_tickets_12_1_2.pptx in the same directory as this script.
'''

import os
from pptx import Presentation
from pptx.util import Inches, Pt, Emu
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN, MSO_ANCHOR
from pptx.oxml.ns import qn

# --- Color constants matching the existing template ---
PURPLE_HEADER = RGBColor(0x7B, 0x2D, 0x8E)  # Purple from the screenshot
WHITE = RGBColor(0xFF, 0xFF, 0xFF)
BLACK = RGBColor(0x00, 0x00, 0x00)
DARK_GRAY = RGBColor(0x33, 0x33, 0x33)
LIGHT_GRAY_BG = RGBColor(0xF2, 0xF2, 0xF2)  # Alternating row shading
CORNELIS_BLUE = RGBColor(0x00, 0x3D, 0x6B)   # Cornelis brand navy

JIRA_BASE = 'https://cornelisnetworks.atlassian.net/browse/'

# --- Slide dimensions (widescreen 16:9) ---
SLIDE_WIDTH = Inches(13.333)
SLIDE_HEIGHT = Inches(7.5)


def set_cell_fill(cell, color):
    '''Set solid fill color on a table cell.'''
    tc = cell._tc
    tcPr = tc.get_or_add_tcPr()
    # Remove any existing fill
    for child in list(tcPr):
        if child.tag.endswith('}solidFill') or child.tag.endswith('}noFill'):
            tcPr.remove(child)
    solidFill = tcPr.makeelement(qn('a:solidFill'), {})
    srgbClr = solidFill.makeelement(qn('a:srgbClr'), {'val': '%02X%02X%02X' % (color[0], color[1], color[2])})
    solidFill.append(srgbClr)
    tcPr.append(solidFill)


def set_cell_border(cell, color=RGBColor(0xCC, 0xCC, 0xCC), width=Pt(0.5)):
    '''Set thin borders on a cell.'''
    tc = cell._tc
    tcPr = tc.get_or_add_tcPr()
    for edge in ['lnL', 'lnR', 'lnT', 'lnB']:
        ln = tcPr.makeelement(qn('a:%s' % edge), {'w': str(int(width))})
        solidFill = ln.makeelement(qn('a:solidFill'), {})
        srgbClr = solidFill.makeelement(qn('a:srgbClr'), {'val': '%02X%02X%02X' % (color[0], color[1], color[2])})
        solidFill.append(srgbClr)
        ln.append(solidFill)
        # Remove existing same-tag element
        for existing in list(tcPr):
            if existing.tag == ln.tag:
                tcPr.remove(existing)
        tcPr.append(ln)


def format_cell(cell, text, font_size=Pt(9), bold=False, color=DARK_GRAY, alignment=PP_ALIGN.LEFT):
    '''Set text content and formatting on a table cell.'''
    cell.text = ''
    tf = cell.text_frame
    tf.word_wrap = True
    tf.auto_size = None
    # Reduce margins for tighter layout
    tf.margin_left = Pt(3)
    tf.margin_right = Pt(3)
    tf.margin_top = Pt(2)
    tf.margin_bottom = Pt(2)
    cell.vertical_anchor = MSO_ANCHOR.TOP

    p = tf.paragraphs[0]
    p.alignment = alignment
    p.space_before = Pt(0)
    p.space_after = Pt(0)
    run = p.add_run()
    run.text = text
    run.font.size = font_size
    run.font.bold = bold
    run.font.color.rgb = color


def format_header_cell(cell, text, font_size=Pt(9)):
    '''Format a header cell with purple background and white bold text.'''
    set_cell_fill(cell, PURPLE_HEADER)
    format_cell(cell, text, font_size=font_size, bold=True, color=WHITE)


def add_hyperlink_cell(slide, cell, ticket_ids, font_size=Pt(8)):
    '''Add cell content with Jira ticket IDs as clickable hyperlinks.
    slide: the slide object (needed for relationship creation).
    ticket_ids: list of ticket ID strings, e.g. ['STL-76950', 'STL-76880'].
    '''
    cell.text = ''
    tf = cell.text_frame
    tf.word_wrap = True
    tf.margin_left = Pt(3)
    tf.margin_right = Pt(3)
    tf.margin_top = Pt(2)
    tf.margin_bottom = Pt(2)
    cell.vertical_anchor = MSO_ANCHOR.TOP

    p = tf.paragraphs[0]
    p.space_before = Pt(0)
    p.space_after = Pt(0)

    for i, ticket_id in enumerate(ticket_ids):
        if i > 0:
            run = p.add_run()
            run.text = '\n'
            run.font.size = font_size

        run = p.add_run()
        run.text = ticket_id
        run.font.size = font_size
        run.font.color.rgb = CORNELIS_BLUE
        run.font.underline = True
        # Create relationship-based hyperlink (actually clickable in PowerPoint)
        url = JIRA_BASE + ticket_id
        rel = slide.part.relate_to(
            url,
            'http://schemas.openxmlformats.org/officeDocument/2006/relationships/hyperlink',
            is_external=True
        )
        rPr = run._r.get_or_add_rPr()
        hlinkClick = rPr.makeelement(qn('a:hlinkClick'), {})
        hlinkClick.set(qn('r:id'), rel)
        rPr.append(hlinkClick)


def add_table(slide, left, top, width, height, rows, cols):
    '''Add a table shape to a slide and return the table object.'''
    table_shape = slide.shapes.add_table(rows, cols, left, top, width, height)
    return table_shape.table


def add_title(slide, text, left=Inches(0.5), top=Inches(0.2), width=Inches(12), height=Inches(0.5)):
    '''Add a title text box to a slide.'''
    txBox = slide.shapes.add_textbox(left, top, width, height)
    tf = txBox.text_frame
    p = tf.paragraphs[0]
    run = p.add_run()
    run.text = text
    run.font.size = Pt(20)
    run.font.bold = True
    run.font.color.rgb = CORNELIS_BLUE
    return txBox


def add_subtitle(slide, text, left=Inches(0.5), top=Inches(0.65), width=Inches(12), height=Inches(0.35)):
    '''Add subtitle text below the title.'''
    txBox = slide.shapes.add_textbox(left, top, width, height)
    tf = txBox.text_frame
    p = tf.paragraphs[0]
    run = p.add_run()
    run.text = text
    run.font.size = Pt(11)
    run.font.color.rgb = DARK_GRAY
    return txBox


# =========================================================================
# BUG TICKET DATA -- sourced from changelog
# Release: HostSoftware 12.1.2.0.3 + BMC 12.1.2.0.2 + FwUpdate 12.1.2.0.1
#          + JKR 12.1.2.0.2 + MYR 12.1.2.0.1
# 208 commits, 30 unique bug ticket Jira IDs
# =========================================================================

def build_overview_data():
    '''Return (headers, rows) for the Slide 1 overview summary table.'''
    headers = ['Category', 'Bug Count', 'Key Tickets']
    rows = [
        [
            'Driver (Host Software)',
            '18',
            'STL-71206, STL-74848, STL-76311, STL-76441, STL-76477, STL-76488, '
            'STL-76662, STL-76676, STL-76747, STL-76962, STL-76982, STL-76983, '
            'STL-76995, STL-76999, STL-77001, STL-77070, STL-77078, STL-77101'
        ],
        [
            'BMCFW',
            '3',
            'STL-76841, STL-77046, STL-77092'
        ],
        [
            'HFIFW',
            '1',
            'STL-77027'
        ],
        [
            'Libfabric',
            '8',
            'STL-63325, STL-76561, STL-76778, STL-76965, STL-76966, '
            'STL-76972, STL-77075, STL-77106'
        ],
        [
            'Total',
            '30',
            ''
        ],
    ]
    return headers, rows


def build_driver_data():
    '''Return (headers, rows) for Slide 2: Driver Bugs (18 tickets).'''
    headers = ['Ticket', 'Summary', 'Author', 'Notes']
    rows = [
        ['STL-71206', 'Fix firmware update MAD response handling over fabric', 'Douglas Miller', ''],
        ['STL-74848', 'Threaded NAPI for IPoIB TX completion -- priority inversion fix', 'Brian Hwang', 'Related: STL-76311, STL-76441'],
        ['STL-76311', 'Threaded NAPI for IPoIB TX completion (related)', 'Brian Hwang', 'Part of STL-74848 fix'],
        ['STL-76441', 'Threaded NAPI for IPoIB TX completion (related)', 'Brian Hwang', 'Part of STL-74848 fix'],
        ['STL-76477', 'Reapply cport MSI-X interrupt', 'Dennis Dalessandro', ''],
        ['STL-76488', 'Reapply disable lost interrupt timer + additional cport interrupt clears', 'Dennis Dalessandro', '2 commits per distro'],
        ['STL-76662', 'Make MCTXT tid xarray interrupt safe -- xa_lock deadlock prevention', 'Douglas Miller', ''],
        ['STL-76676', 'SDMA header optimization bug fixes -- 128B buffer overflow, head/tail fixup', 'Pooja Nara', 'Co-authored: Claude:claude-4.5-opus'],
        ['STL-76747', 'Simplify receive context processing -- remove vtable/function pointer', 'Ian Simonson', ''],
        ['STL-76962', 'Multiple DMS/bulksvc fixes (5 commits) -- teardown ordering, PIO -EAGAIN, WARN_ON completions, DMA page count, SDMA bounds', 'Michael Blocksome', ''],
        ['STL-76982', 'DMS access unregister rework (4 commits) -- completion handling, user_info clear, use-after-free in QP send, invalid-client log', 'Michael Blocksome / Ian Simonson', ''],
        ['STL-76983', 'Switch DMS access unregister to passive-only, remove force-cancel', 'Michael Blocksome', ''],
        ['STL-76995', 'Multiple MR/bulksvc leak fixes (4 commits) -- list sentinel deref, DMA mapping leak, cmd/mr_record leaks, rvt_mr ref leak', 'Ian Simonson', ''],
        ['STL-76999', 'Fix bulksvc_dbg_open unbounded spin-wait deadlock', 'Michael Blocksome', ''],
        ['STL-77001', 'Tone down DMS health timeout log wording', 'Michael Blocksome', ''],
        ['STL-77070', 'Fix use-after-free in cport_req_fn()', 'Douglas Miller', ''],
        ['STL-77078', 'Restrict send scheduling checks to RESET state', 'Michael Blocksome / Ian Simonson', ''],
        ['STL-77101', 'Only print perf counters if counted', 'Nick Child', ''],
    ]
    return headers, rows


def build_bmcfw_data():
    '''Return (headers, rows) for Slide 3: BMCFW Bugs (3 tickets).'''
    headers = ['Ticket', 'Summary', 'Author', 'Notes']
    rows = [
        ['STL-76841', 'CLI capture log bytes/str error', 'Duane McCrory', ''],
        ['STL-77046', 'BMC FruDevice introspect fail', 'Duane McCrory', ''],
        ['STL-77092', 'Lenovo DWC VR fault error', 'Duane McCrory', 'NEW in BMC 12.1.2.0.2'],
    ]
    return headers, rows


def build_hfifw_data():
    '''Return (headers, rows) for Slide 4: HFIFW Bug (1 ticket).'''
    headers = ['Ticket', 'Summary', 'Author', 'Notes']
    rows = [
        ['STL-77027', 'Cannot Start Second FM -- forward PortInfo GET to driver, save IsSM state', 'Paul Davis / Daniel Gailey', ''],
    ]
    return headers, rows


def build_libfabric_data():
    '''Return (headers, rows) for Slide 5: Libfabric Bugs (8 tickets).'''
    headers = ['Ticket', 'Summary', 'Author', 'Notes']
    rows = [
        ['STL-63325', 'Remove #if 0 dead code', 'Bob Cernohous', ''],
        ['STL-76561', 'Multiple mm lock / rendezvous fixes (5 commits)', 'Bob Cernohous', ''],
        ['STL-76778', 'Change all CUDA calls to use ofi wrapper functions', 'Mike Wilkins', ''],
        ['STL-76965', 'Dual plane multiple tx and ibv context', 'Archana Venkatesha', ''],
        ['STL-76966', 'Dual plane addressing, plane selection and shm', 'Archana Venkatesha', ''],
        ['STL-76972', 'Restore debugging #ifdef', 'Bob Cernohous', ''],
        ['STL-77075', 'SLES compilation fix', 'Archana Venkatesha', ''],
        ['STL-77106', 'PCI bus attributes from sysfs', 'Dennis Dalessandro', ''],
    ]
    return headers, rows


def create_presentation():
    '''Build the full PowerPoint presentation (changelog bug tickets).'''
    prs = Presentation()
    # Set 16:9 widescreen
    prs.slide_width = SLIDE_WIDTH
    prs.slide_height = SLIDE_HEIGHT

    # Use blank layout
    blank_layout = prs.slide_layouts[6]  # Blank

    # ===== SLIDE 1: Overview =====
    slide = prs.slides.add_slide(blank_layout)
    add_title(slide, 'Bug Tickets Resolved in Release 12.1.2')
    add_subtitle(
        slide,
        'Source: changelog_Release_HostSoftware12_1_2_0_3BMC12_1_2_0_2...  |  '
        'Generated 2026-03-26  |  208 commits, 30 bug tickets'
    )

    # Overview summary table
    headers, rows = build_overview_data()
    n_rows = len(rows) + 1  # +1 for header
    n_cols = len(headers)
    tbl_left = Inches(0.5)
    tbl_top = Inches(1.2)
    tbl_width = Inches(12.3)
    # 6 rows (1 header + 5 data), ~0.45 inches each
    tbl_height = Inches(n_rows * 0.45)

    table = add_table(slide, tbl_left, tbl_top, tbl_width, tbl_height, n_rows, n_cols)

    # Column widths: Category, Bug Count, Key Tickets
    col_widths = [2.0, 1.2, 9.1]
    for i, w in enumerate(col_widths):
        table.columns[i].width = Inches(w)

    # Header row
    for i, h in enumerate(headers):
        format_header_cell(table.cell(0, i), h, font_size=Pt(9))

    # Data rows
    for r_idx, row in enumerate(rows):
        for c_idx, val in enumerate(row):
            cell = table.cell(r_idx + 1, c_idx)
            # Bold the Total row
            is_bold = (row[0] == 'Total')
            format_cell(cell, val, font_size=Pt(8), bold=is_bold, color=DARK_GRAY)
            # Alternating row fill
            if r_idx % 2 == 1:
                set_cell_fill(cell, LIGHT_GRAY_BG)
            else:
                set_cell_fill(cell, WHITE)
            set_cell_border(cell)

    # ===== SLIDE 2: Driver Bugs (18 tickets) =====
    slide = prs.slides.add_slide(blank_layout)
    add_title(slide, 'Driver Bugs (18 tickets)')
    add_subtitle(slide, 'Host Software 12.1.2.0.3 -- kernel driver fixes backported across 7 distro branches')

    headers, rows = build_driver_data()
    n_rows = len(rows) + 1  # 18 data + 1 header = 19
    n_cols = len(headers)
    tbl_left = Inches(0.5)
    tbl_top = Inches(1.1)
    tbl_width = Inches(12.3)
    # 19 rows at ~0.30 inches each to fit on slide
    tbl_height = Inches(min(n_rows * 0.30, 5.8))

    table = add_table(slide, tbl_left, tbl_top, tbl_width, tbl_height, n_rows, n_cols)

    # Column widths: Ticket, Summary, Author, Notes
    col_widths_detail = [1.0, 6.0, 2.3, 3.0]
    for i, w in enumerate(col_widths_detail):
        table.columns[i].width = Inches(w)

    # Header row
    for i, h in enumerate(headers):
        format_header_cell(table.cell(0, i), h, font_size=Pt(8))

    # Data rows
    for r_idx, row in enumerate(rows):
        for c_idx, val in enumerate(row):
            cell = table.cell(r_idx + 1, c_idx)
            if c_idx == 0:
                # Ticket column -- clickable Jira hyperlink
                add_hyperlink_cell(slide, cell, [val], font_size=Pt(7))
            else:
                format_cell(cell, val, font_size=Pt(7), bold=False, color=DARK_GRAY)
            # Alternating row fill
            if r_idx % 2 == 1:
                set_cell_fill(cell, LIGHT_GRAY_BG)
            else:
                set_cell_fill(cell, WHITE)
            set_cell_border(cell)

    # Footnote below the driver table
    footnote_top = tbl_top + tbl_height + Inches(0.15)
    fn_box = slide.shapes.add_textbox(Inches(0.5), footnote_top, Inches(12.0), Inches(0.4))
    fn_tf = fn_box.text_frame
    fn_p = fn_tf.paragraphs[0]
    fn_run = fn_p.add_run()
    fn_run.text = (
        'All 18 driver fixes are backported across 7 distro branches: '
        'RHEL 10, RHEL 9.4, RHEL 9.5, RHEL 9.6, RHEL 9.7, SLES 15.7, Ubuntu 24.04'
    )
    fn_run.font.size = Pt(10)
    fn_run.font.italic = True
    fn_run.font.color.rgb = DARK_GRAY

    # ===== SLIDE 3: BMCFW Bugs (3 tickets) =====
    slide = prs.slides.add_slide(blank_layout)
    add_title(slide, 'BMCFW Bugs (3 tickets)')
    add_subtitle(slide, 'BMC 12.1.2.0.2 -- BMC firmware fixes')

    headers, rows = build_bmcfw_data()
    n_rows = len(rows) + 1  # 3 data + 1 header = 4
    n_cols = len(headers)
    tbl_left = Inches(0.5)
    tbl_top = Inches(1.1)
    tbl_width = Inches(12.3)
    tbl_height = Inches(n_rows * 0.45)

    table = add_table(slide, tbl_left, tbl_top, tbl_width, tbl_height, n_rows, n_cols)

    col_widths_detail = [1.0, 6.0, 2.3, 3.0]
    for i, w in enumerate(col_widths_detail):
        table.columns[i].width = Inches(w)

    for i, h in enumerate(headers):
        format_header_cell(table.cell(0, i), h, font_size=Pt(9))

    for r_idx, row in enumerate(rows):
        for c_idx, val in enumerate(row):
            cell = table.cell(r_idx + 1, c_idx)
            if c_idx == 0:
                add_hyperlink_cell(slide, cell, [val], font_size=Pt(8))
            else:
                format_cell(cell, val, font_size=Pt(8), bold=False, color=DARK_GRAY)
            if r_idx % 2 == 1:
                set_cell_fill(cell, LIGHT_GRAY_BG)
            else:
                set_cell_fill(cell, WHITE)
            set_cell_border(cell)

    # ===== SLIDE 4: HFIFW Bug (1 ticket) =====
    slide = prs.slides.add_slide(blank_layout)
    add_title(slide, 'HFIFW Bug (1 ticket)')
    add_subtitle(slide, 'FwUpdate 12.1.2.0.1 -- HFI firmware fix')

    headers, rows = build_hfifw_data()
    n_rows = len(rows) + 1  # 1 data + 1 header = 2
    n_cols = len(headers)
    tbl_left = Inches(0.5)
    tbl_top = Inches(1.1)
    tbl_width = Inches(12.3)
    tbl_height = Inches(n_rows * 0.45)

    table = add_table(slide, tbl_left, tbl_top, tbl_width, tbl_height, n_rows, n_cols)

    col_widths_detail = [1.0, 6.0, 2.3, 3.0]
    for i, w in enumerate(col_widths_detail):
        table.columns[i].width = Inches(w)

    for i, h in enumerate(headers):
        format_header_cell(table.cell(0, i), h, font_size=Pt(9))

    for r_idx, row in enumerate(rows):
        for c_idx, val in enumerate(row):
            cell = table.cell(r_idx + 1, c_idx)
            if c_idx == 0:
                add_hyperlink_cell(slide, cell, [val], font_size=Pt(8))
            else:
                format_cell(cell, val, font_size=Pt(8), bold=False, color=DARK_GRAY)
            if r_idx % 2 == 1:
                set_cell_fill(cell, LIGHT_GRAY_BG)
            else:
                set_cell_fill(cell, WHITE)
            set_cell_border(cell)

    # ===== SLIDE 5: Libfabric Bugs (8 tickets) =====
    slide = prs.slides.add_slide(blank_layout)
    add_title(slide, 'Libfabric Bugs (8 tickets)')
    add_subtitle(slide, 'Host Software 12.1.2.0.3 -- OPX/libfabric provider fixes')

    headers, rows = build_libfabric_data()
    n_rows = len(rows) + 1  # 8 data + 1 header = 9
    n_cols = len(headers)
    tbl_left = Inches(0.5)
    tbl_top = Inches(1.1)
    tbl_width = Inches(12.3)
    tbl_height = Inches(n_rows * 0.40)

    table = add_table(slide, tbl_left, tbl_top, tbl_width, tbl_height, n_rows, n_cols)

    col_widths_detail = [1.0, 6.0, 2.3, 3.0]
    for i, w in enumerate(col_widths_detail):
        table.columns[i].width = Inches(w)

    for i, h in enumerate(headers):
        format_header_cell(table.cell(0, i), h, font_size=Pt(9))

    for r_idx, row in enumerate(rows):
        for c_idx, val in enumerate(row):
            cell = table.cell(r_idx + 1, c_idx)
            if c_idx == 0:
                add_hyperlink_cell(slide, cell, [val], font_size=Pt(8))
            else:
                format_cell(cell, val, font_size=Pt(8), bold=False, color=DARK_GRAY)
            if r_idx % 2 == 1:
                set_cell_fill(cell, LIGHT_GRAY_BG)
            else:
                set_cell_fill(cell, WHITE)
            set_cell_border(cell)

    # Save
    output_dir = os.path.dirname(os.path.abspath(__file__))
    output_path = os.path.join(output_dir, 'changelog_bug_tickets_12_1_2.pptx')
    prs.save(output_path)
    print('Saved: %s' % output_path)
    return output_path


if __name__ == '__main__':
    create_presentation()
