##########
# Script: generate_critical_issue_p0_slides.py
# Description: Generate PowerPoint slides for Critical Issue Status (P0-Only)
# Author: John Macdonald (generated by OpenCode)
##########
'''
Generates critical_issue_status_p0_2026-03-26.pptx from P0-only bug data
sourced from Jira filter 33606 (SW 12.1.2 Targeted P0 Bugs).

Matches the existing slide template style (purple headers, white rows, 16:9).
Produces: Scoreboard + Rollup (Slide 1), 4 detail slides, Root Cause Summary.

Usage:
    python generate_critical_issue_p0_slides.py

Output:
    critical_issue_status_p0_2026-03-26.pptx in the same directory as this script.
'''

import os
from pptx import Presentation
from pptx.util import Inches, Pt, Emu
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN, MSO_ANCHOR
from pptx.oxml.ns import qn

# --- Color constants matching the existing template ---
PURPLE_HEADER = RGBColor(0x7B, 0x2D, 0x8E)  # Purple from the screenshot
WHITE = RGBColor(0xFF, 0xFF, 0xFF)
BLACK = RGBColor(0x00, 0x00, 0x00)
DARK_GRAY = RGBColor(0x33, 0x33, 0x33)
LIGHT_GRAY_BG = RGBColor(0xF2, 0xF2, 0xF2)  # Alternating row shading
CORNELIS_BLUE = RGBColor(0x00, 0x3D, 0x6B)   # Cornelis brand navy

JIRA_BASE = 'https://cornelisnetworks.atlassian.net/browse/'

# --- Slide dimensions (widescreen 16:9) ---
SLIDE_WIDTH = Inches(13.333)
SLIDE_HEIGHT = Inches(7.5)


def set_cell_fill(cell, color):
    '''Set solid fill color on a table cell.'''
    tc = cell._tc
    tcPr = tc.get_or_add_tcPr()
    # Remove any existing fill
    for child in list(tcPr):
        if child.tag.endswith('}solidFill') or child.tag.endswith('}noFill'):
            tcPr.remove(child)
    solidFill = tcPr.makeelement(qn('a:solidFill'), {})
    srgbClr = solidFill.makeelement(qn('a:srgbClr'), {'val': '%02X%02X%02X' % (color[0], color[1], color[2])})
    solidFill.append(srgbClr)
    tcPr.append(solidFill)


def set_cell_border(cell, color=RGBColor(0xCC, 0xCC, 0xCC), width=Pt(0.5)):
    '''Set thin borders on a cell.'''
    tc = cell._tc
    tcPr = tc.get_or_add_tcPr()
    for edge in ['lnL', 'lnR', 'lnT', 'lnB']:
        ln = tcPr.makeelement(qn('a:%s' % edge), {'w': str(int(width))})
        solidFill = ln.makeelement(qn('a:solidFill'), {})
        srgbClr = solidFill.makeelement(qn('a:srgbClr'), {'val': '%02X%02X%02X' % (color[0], color[1], color[2])})
        solidFill.append(srgbClr)
        ln.append(solidFill)
        # Remove existing same-tag element
        for existing in list(tcPr):
            if existing.tag == ln.tag:
                tcPr.remove(existing)
        tcPr.append(ln)


def format_cell(cell, text, font_size=Pt(9), bold=False, color=DARK_GRAY, alignment=PP_ALIGN.LEFT):
    '''Set text content and formatting on a table cell.'''
    cell.text = ''
    tf = cell.text_frame
    tf.word_wrap = True
    tf.auto_size = None
    # Reduce margins for tighter layout
    tf.margin_left = Pt(3)
    tf.margin_right = Pt(3)
    tf.margin_top = Pt(2)
    tf.margin_bottom = Pt(2)
    cell.vertical_anchor = MSO_ANCHOR.TOP

    p = tf.paragraphs[0]
    p.alignment = alignment
    p.space_before = Pt(0)
    p.space_after = Pt(0)
    run = p.add_run()
    run.text = text
    run.font.size = font_size
    run.font.bold = bold
    run.font.color.rgb = color


def format_header_cell(cell, text, font_size=Pt(9)):
    '''Format a header cell with purple background and white bold text.'''
    set_cell_fill(cell, PURPLE_HEADER)
    format_cell(cell, text, font_size=font_size, bold=True, color=WHITE)


def add_hyperlink_cell(slide, cell, ticket_ids, font_size=Pt(8)):
    '''Add cell content with Jira ticket IDs as clickable hyperlinks.
    slide: the slide object (needed for relationship creation).
    ticket_ids: list of ticket ID strings, e.g. ['STL-76950', 'STL-76880'].
    '''
    cell.text = ''
    tf = cell.text_frame
    tf.word_wrap = True
    tf.margin_left = Pt(3)
    tf.margin_right = Pt(3)
    tf.margin_top = Pt(2)
    tf.margin_bottom = Pt(2)
    cell.vertical_anchor = MSO_ANCHOR.TOP

    p = tf.paragraphs[0]
    p.space_before = Pt(0)
    p.space_after = Pt(0)

    for i, ticket_id in enumerate(ticket_ids):
        if i > 0:
            run = p.add_run()
            run.text = '\n'
            run.font.size = font_size

        run = p.add_run()
        run.text = ticket_id
        run.font.size = font_size
        run.font.color.rgb = CORNELIS_BLUE
        run.font.underline = True
        # Create relationship-based hyperlink (actually clickable in PowerPoint)
        url = JIRA_BASE + ticket_id
        rel = slide.part.relate_to(
            url,
            'http://schemas.openxmlformats.org/officeDocument/2006/relationships/hyperlink',
            is_external=True
        )
        rPr = run._r.get_or_add_rPr()
        hlinkClick = rPr.makeelement(qn('a:hlinkClick'), {})
        hlinkClick.set(qn('r:id'), rel)
        rPr.append(hlinkClick)


def add_table(slide, left, top, width, height, rows, cols):
    '''Add a table shape to a slide and return the table object.'''
    table_shape = slide.shapes.add_table(rows, cols, left, top, width, height)
    return table_shape.table


def add_title(slide, text, left=Inches(0.5), top=Inches(0.2), width=Inches(12), height=Inches(0.5)):
    '''Add a title text box to a slide.'''
    txBox = slide.shapes.add_textbox(left, top, width, height)
    tf = txBox.text_frame
    p = tf.paragraphs[0]
    run = p.add_run()
    run.text = text
    run.font.size = Pt(20)
    run.font.bold = True
    run.font.color.rgb = CORNELIS_BLUE
    return txBox


def add_subtitle(slide, text, left=Inches(0.5), top=Inches(0.65), width=Inches(12), height=Inches(0.35)):
    '''Add subtitle text below the title.'''
    txBox = slide.shapes.add_textbox(left, top, width, height)
    tf = txBox.text_frame
    p = tf.paragraphs[0]
    run = p.add_run()
    run.text = text
    run.font.size = Pt(11)
    run.font.color.rgb = DARK_GRAY
    return txBox


# =========================================================================
# P0-ONLY DATA — sourced from Jira filter 33606, queried 2026-03-26
# 23 total P0 bugs: 12 active, 6 Verify, 5 Closed
# =========================================================================

def build_rollup_table_data():
    '''Return (headers, rows) for the Slide 1 rollup table.
    12 active P0 bugs clustered into 8 root-cause rows.
    '''
    headers = ['Area', 'Issues', 'Description', 'Customer', 'Status', 'Next Steps']
    rows = [
        [
            'BTS / Lustre',
            'STL-76950\nSTL-76880\nSTL-76940',
            'GPU DMA-buf deregistration race \u2014 mi300x kernel panics in rdmavt + Lustre RDMA timeouts. All hit same BTS memory lifecycle path.',
            '\u2014',
            'In Review /\nInvestigating',
            '76950 fix in review (Child); blocked by 76982 (Verify) + 76983, 76984 (Open). If all land \u2192 cascade-fixes cluster.'
        ],
        [
            'OPX \u2014 TID cache',
            'STL-76365\nSTL-73247',
            'OPX TID cache diverges from kernel TID table under high expected-receive rate. HPL + sph_exa hangs. Chronic \u2014 73247 open since 12.1.0.x.',
            '\u2014',
            'Investigating',
            'Architecturally complex fix spanning OPX user-space + hfi1 kernel. Cernohous + Erwin.'
        ],
        [
            'OPX \u2014 GPU AI',
            'STL-77071',
            'MPT-30B hang with aws-ofi dmabuf. May overlap BTS DMA-buf cluster. New this week.',
            'RWTH',
            'Investigating',
            'Espinoza assessing. Possible user config issue \u2014 engaging customer.'
        ],
        [
            'Fabric / MYR FW',
            'STL-76338\nSTL-76494',
            'MYR switch buffer/credit mgmt \u2014 tportPktDropPending on ISLs, RbufCtrlSbe hung nodes. 76494 has sw_fixed workaround.',
            'TACC',
            'Investigating',
            'Wright on ISL drops. Rothermel on RbufCtrlSbe. No fixes landed yet.'
        ],
        [
            'Fabric / MYR FW',
            'STL-77092',
            'DWC switch VR fault on liquid-cooled switch. HW issue, separate from buffer/credit. New this week.',
            'Lenovo',
            'In Review',
            'Nagarajan fix in review.'
        ],
        [
            'Host Driver \u2014\nIPoIB',
            'STL-76836',
            'ipoib timeout at LLNL Lynx. May be fabric-caused \u2014 links to 76494 (RbufCtrlSbe) + 76873 (link training).',
            'LLNL (Lynx)',
            'Investigating',
            'Correlate with fabric cluster. If fabric-side, reclassify.'
        ],
        [
            'Host Driver \u2014\nPCIe',
            'STL-76997',
            'Jobs crashed during SPEC run at NEC/RWTH. PCIe uncorrectable error correlation. Relates to STL-75193.',
            'NEC/RWTH',
            'Investigating',
            'Luick investigating. Koch providing lspci output.'
        ],
        [
            'Link / 8051 FW',
            'STL-76873',
            'Link fails LNI during EstablishComm.TxRxHunt \u2014 8051 FW SerDes link training. ~8 links affected.',
            'LLNL (Lynx)',
            'Investigating',
            'Johanson leading via Link Working Group.'
        ],
    ]
    return headers, rows


def build_detail_data():
    '''Return detail slide data as list of dicts (P0-only).'''
    slides = []

    # --- BTS / Lustre ---
    slides.append({
        'title': 'BTS / Lustre \u2014 Detail',
        'subtitle': '3 active + 5 in Verify \u2014 BTS memory deregistration race is the core root cause',
        'sections': [
            {
                'label': 'Active (3 bugs)',
                'headers': ['Issue', 'Pri', 'Summary', 'Assignee', 'Status', 'Root Cause / Blockers', 'Next Steps'],
                'col_widths': [0.9, 0.5, 2.0, 0.8, 0.7, 3.2, 2.5],
                'rows': [
                    ['STL-76950', 'P0', 'mi300x crash on ctl-c BTS/dmabuf \u2014 bulksvc_user_info_destroy', 'Child', 'In Review',
                     'GPU DMA-buf deregistration race. Blocked by:\nSTL-76982 (DMS unregister, Verify)\nSTL-76983 (force-cancel trackers, Open)\nSTL-76984 (rvt/bulksvc race, Open)',
                     'Retest with next DST once all 3 blockers land.'],
                    ['STL-76880', 'P0', 'mi300x GPU kernel panic rvt_send_complete', 'Simonson', 'Investigating',
                     'Same rdmavt DMA-buf path as 76950.',
                     'Likely fixed by 76950 patches. Retest together.'],
                    ['STL-76940', 'P0', 'LNetError RDMA timeout with BTS \u2014 Lustre client eviction', 'Simonson', 'Investigating',
                     'Lustre ko2iblnd hits BTS verbs path.\nCaused by STL-76941 (Verify).\nBlocked by STL-76999 (Verify).',
                     'Zhu: "Wait for 12.1.2 DST \u2014 fixed a few bugs."'],
                ],
            },
            {
                'label': 'Verify Queue (5 P0 BTS fixes awaiting validation)',
                'headers': ['Issue', 'Summary', 'What It Fixes'],
                'col_widths': [1.2, 5.0, 4.4],
                'rows': [
                    ['STL-76999', 'Fix bulksvc_dbg_open unbounded spin-wait deadlock', 'Blocks 76940 (Lustre RDMA timeout)'],
                    ['STL-76942', 'bufcount error \u2014 BTS buffer management', 'BTS Lustre data integrity'],
                    ['STL-76863', 'BAD WRITE CHECKSUM \u2014 BTS MR registration error', 'BTS Lustre data integrity'],
                    ['STL-76847', 'calculate_mr_page_offset Invalid', 'BTS Lustre data integrity'],
                    ['STL-76732', 'hfi1_dms_impl_dlist_remove crash \u2014 DMS list corruption', 'BTS internal locking'],
                ],
            },
        ],
    })

    # --- OPX ---
    slides.append({
        'title': 'OPX \u2014 Detail',
        'subtitle': '3 active + 1 in Verify \u2014 TID cache is chronic; new GPU AI hang needs triage',
        'sections': [
            {
                'label': 'Active (3 bugs)',
                'headers': ['Issue', 'Pri', 'Summary', 'Assignee', 'Status', 'Customer', 'Root Cause', 'Next Steps'],
                'col_widths': [0.9, 0.4, 1.8, 0.7, 0.6, 0.6, 2.5, 2.2],
                'rows': [
                    ['STL-76365', 'P0', 'HPL hang in hfi1_user_exp_rcv_setup', 'Cernohous', 'Investigating', '\u2014',
                     'OPX TID cache diverges from kernel. Links to 76561, 76972, 76685, 76554.',
                     'Fix spans OPX user-space + hfi1 kernel.'],
                    ['STL-73247', 'P0', 'sph_exa hang with OPX Open MPI', 'Erwin', 'Investigating', '\u2014',
                     'Same TID cache root cause. Open since 12.1.0.x.',
                     'Same fix as 76365.'],
                    ['STL-77071', 'P0', 'MPT-30B hang aws-ofi dmabuf', 'Espinoza', 'Investigating', 'RWTH',
                     'Possibly OPX+DMA-buf. May be user config.',
                     'Engaging RWTH directly.'],
                ],
            },
            {
                'label': 'Verify Queue (1 OPX fix)',
                'headers': ['Issue', 'Summary', 'What It Fixes'],
                'col_widths': [1.2, 5.0, 4.4],
                'rows': [
                    ['STL-76561', 'HPL OPX_TID_CACHE assert with use_bulksvc:N', 'Related to TID cache cluster (76365, 73247)'],
                ],
            },
        ],
    })

    # --- Fabric / MYR FW ---
    slides.append({
        'title': 'Fabric / MYR FW \u2014 Detail',
        'subtitle': '3 active \u2014 Buffer/credit cluster: 2 bugs, zero fixes landed. VR fault close to landing.',
        'sections': [
            {
                'label': 'Active (3 bugs)',
                'headers': ['Issue', 'Pri', 'Summary', 'Assignee', 'Status', 'Customer', 'Root Cause', 'Next Steps'],
                'col_widths': [0.9, 0.4, 1.8, 0.7, 0.6, 0.5, 2.5, 2.3],
                'rows': [
                    ['STL-76338', 'P0', 'tportPktDropPending hang on ISL bounce', 'Wright', 'Investigating', 'TACC',
                     'MYR Tport state machine. Links to 76651, 76652, ISS-8041.',
                     'Reproduced internally. Wright analyzing.'],
                    ['STL-76494', 'P0', 'Hung nodes \u2014 RbufCtrlSbe ECC errors', 'Rothermel', 'Investigating', 'TACC',
                     'SRAM bit errors corrupt buffer mgmt. sw_fixed label. Links to 76836, 77090.',
                     'SW workaround exists. Watch SBE rate for HW degradation.'],
                    ['STL-77092', 'P0', 'DWC switch VR fault (liquid-cooled)', 'Nagarajan', 'In Review', 'Lenovo',
                     'Voltage regulator HW fault. Separate from buffer/credit.',
                     'Fix in review.'],
                ],
            },
        ],
    })

    # --- Host Driver + Link / 8051 FW ---
    slides.append({
        'title': 'Host Driver + Link / 8051 FW \u2014 Detail',
        'subtitle': '3 active \u2014 76836 (LLNL ipoib) may be fabric-caused; 76873 (link training) feeds the picture',
        'sections': [
            {
                'label': 'Active (3 bugs)',
                'headers': ['Issue', 'Pri', 'Summary', 'Assignee', 'Status', 'Customer', 'Root Cause', 'Next Steps'],
                'col_widths': [0.9, 0.4, 1.6, 0.7, 0.6, 0.7, 2.6, 2.2],
                'rows': [
                    ['STL-76836', 'P0', 'ipoib timeout at LLNL Lynx', 'Novak', 'Investigating', 'LLNL',
                     'IPoIB/SDMA path. Links to 76494 (RbufCtrlSbe) + 76873 (link training). May be fabric-caused.',
                     'Correlate with fabric cluster. If fabric-side, reclassify.'],
                    ['STL-76997', 'P0', 'Job crashes during SPEC run', 'Luick', 'Investigating', 'NEC/RWTH',
                     'Relates to 75193 (PCIe fatal error). Investigating uncorrectable error correlation.',
                     'Koch providing lspci. Luick proceeding with investigation.'],
                    ['STL-76873', 'P0', 'Link fails LNI EstablishComm.TxRxHunt', 'Johanson', 'Investigating', 'LLNL',
                     '8051 FW SerDes link training. ~8 links not coming up. Links to 76836 (ipoib).',
                     'Johanson leading via Link Working Group.'],
                ],
            },
        ],
    })

    return slides


def create_presentation():
    '''Build the full PowerPoint presentation (P0-only).'''
    prs = Presentation()
    # Set 16:9 widescreen
    prs.slide_width = SLIDE_WIDTH
    prs.slide_height = SLIDE_HEIGHT

    # Use blank layout
    blank_layout = prs.slide_layouts[6]  # Blank

    # ===== SLIDE 1: Scoreboard + Rollup =====
    slide = prs.slides.add_slide(blank_layout)
    add_title(slide, 'Critical Issue Status (P0 Only) \u2014 2026-03-26')
    add_subtitle(slide, 'Source: Jira filter "SW 12.1.2 Targeted P0 Bugs" (33606)  |  23 P0 bugs: 12 active, 6 Verify, 5 Closed')

    # Scoreboard row
    sb_left = Inches(0.5)
    sb_top = Inches(1.05)
    sb_width = Inches(10.0)
    sb_height = Inches(0.55)
    sb_table = add_table(slide, sb_left, sb_top, sb_width, sb_height, 2, 4)

    sb_headers = ['Open Critical', 'New This Week', 'Waiting for Verify in DST', 'Investigating']
    sb_values = ['12', '3', '6', '10']
    for i, (h, v) in enumerate(zip(sb_headers, sb_values)):
        sb_table.columns[i].width = Inches(2.5)
        format_header_cell(sb_table.cell(0, i), h, font_size=Pt(10))
        sb_table.cell(0, i).text_frame.paragraphs[0].alignment = PP_ALIGN.CENTER
        format_cell(sb_table.cell(1, i), v, font_size=Pt(18), bold=True, color=CORNELIS_BLUE, alignment=PP_ALIGN.CENTER)
        set_cell_fill(sb_table.cell(1, i), WHITE)

    # Rollup table
    headers, rows = build_rollup_table_data()
    n_rows = len(rows) + 1  # +1 for header
    n_cols = len(headers)
    tbl_left = Inches(0.3)
    tbl_top = Inches(1.75)
    tbl_width = Inches(12.7)
    tbl_height = Inches(5.5)

    table = add_table(slide, tbl_left, tbl_top, tbl_width, tbl_height, n_rows, n_cols)

    # Column widths: Area, Issues, Description, Customer, Status, Next Steps
    col_widths = [1.1, 1.0, 3.8, 0.9, 0.9, 5.0]
    for i, w in enumerate(col_widths):
        table.columns[i].width = Inches(w)

    # Header row
    for i, h in enumerate(headers):
        format_header_cell(table.cell(0, i), h, font_size=Pt(9))

    # Data rows — Issues column (index 1) gets clickable hyperlinks
    for r_idx, row in enumerate(rows):
        for c_idx, val in enumerate(row):
            cell = table.cell(r_idx + 1, c_idx)
            if c_idx == 1:
                ticket_ids = [t.strip() for t in val.split('\n') if t.strip()]
                add_hyperlink_cell(slide, cell, ticket_ids, font_size=Pt(8))
            else:
                is_bold = (c_idx == 0)
                format_cell(cell, val, font_size=Pt(8), bold=is_bold, color=DARK_GRAY)
            if r_idx % 2 == 1:
                set_cell_fill(cell, LIGHT_GRAY_BG)
            else:
                set_cell_fill(cell, WHITE)
            set_cell_border(cell)

    # ===== DETAIL SLIDES =====
    detail_slides = build_detail_data()

    for detail in detail_slides:
        slide = prs.slides.add_slide(blank_layout)
        add_title(slide, detail['title'])
        add_subtitle(slide, detail['subtitle'])

        current_top = Inches(1.1)

        for section in detail['sections']:
            # Section label
            label_box = slide.shapes.add_textbox(Inches(0.5), current_top, Inches(8), Inches(0.3))
            tf = label_box.text_frame
            p = tf.paragraphs[0]
            run = p.add_run()
            run.text = section['label']
            run.font.size = Pt(11)
            run.font.bold = True
            run.font.color.rgb = DARK_GRAY
            current_top += Inches(0.35)

            headers = section['headers']
            rows = section['rows']
            col_widths = section['col_widths']
            n_rows = len(rows) + 1
            n_cols = len(headers)

            # Calculate total width from col_widths
            total_w = sum(col_widths)
            # Scale to fit 12.3 inches
            scale = 12.3 / total_w
            scaled_widths = [w * scale for w in col_widths]

            # Estimate row height
            row_h = 0.35
            tbl_height = Inches(min((n_rows * row_h), 4.0))

            table = add_table(slide, Inches(0.5), current_top, Inches(12.3), tbl_height, n_rows, n_cols)

            for i, w in enumerate(scaled_widths):
                table.columns[i].width = Inches(w)

            # Header
            for i, h in enumerate(headers):
                format_header_cell(table.cell(0, i), h, font_size=Pt(8))

            # Data
            for r_idx, row in enumerate(rows):
                for c_idx, val in enumerate(row):
                    cell = table.cell(r_idx + 1, c_idx)
                    is_bold = False
                    font_sz = Pt(8)
                    format_cell(cell, val, font_size=font_sz, bold=is_bold, color=DARK_GRAY)
                    if r_idx % 2 == 1:
                        set_cell_fill(cell, LIGHT_GRAY_BG)
                    else:
                        set_cell_fill(cell, WHITE)
                    set_cell_border(cell)

                    if c_idx == 0 and val.startswith('STL-'):
                        add_hyperlink_cell(slide, cell, [val], font_size=Pt(8))

            current_top += tbl_height + Inches(0.2)

    # ===== SLIDE 6: P0 Tickets in Release Changelogs =====
    slide = prs.slides.add_slide(blank_layout)
    add_title(slide, 'P0 Tickets in Release Changelogs')
    add_subtitle(slide, 'Cross-reference: P0 bugs from filter 33606 that have fixes committed in release changelogs')

    # Changelog cross-reference table: 5 columns, 4 data rows + 1 header
    cl_headers = ['P0 Ticket', 'Slide Status', 'Changelog Release', 'Fix Description', 'Author']
    cl_col_widths = [1.2, 1.3, 3.0, 4.0, 2.0]  # total 11.5, scale to 12.3
    cl_total_w = sum(cl_col_widths)
    cl_scale = 12.3 / cl_total_w
    cl_scaled_widths = [w * cl_scale for w in cl_col_widths]

    cl_rows = [
        ['STL-76999', 'Verify',
         'Host Software 12.1.2.0.3 (12_1_2_0_3)',
         'Fix bulksvc_dbg_open unbounded spin-wait deadlock',
         'Michael Blocksome'],
        ['STL-77078', 'Closed (User Verified)',
         'Host Software 12.1.2.0.3 (12_1_2_0_3)',
         'Restrict send scheduling checks to RESET state',
         'Michael Blocksome / Ian Simonson'],
        ['STL-76561', 'Verify',
         'Host Software 12.1.2.0.3 (12_1_2_0_3)',
         'Multiple mm lock / rendezvous fixes (5 commits)',
         'Bob Cernohous'],
        ['STL-76338', 'Investigating (In Progress)',
         'JKR 12.1.0.1.1 / MYR 12.1.0.1.1 / FwUpdate 12.1.0.1.1',
         'Updated pkt drop pending recovery recipe for MYR',
         'Paul Davis'],
    ]

    cl_n_rows = len(cl_rows) + 1  # +1 for header
    cl_n_cols = len(cl_headers)
    cl_tbl_top = Inches(1.1)
    cl_tbl_height = Inches(min(cl_n_rows * 0.45, 4.0))

    cl_table = add_table(slide, Inches(0.5), cl_tbl_top, Inches(12.3), cl_tbl_height, cl_n_rows, cl_n_cols)

    for i, w in enumerate(cl_scaled_widths):
        cl_table.columns[i].width = Inches(w)

    # Header row
    for i, h in enumerate(cl_headers):
        format_header_cell(cl_table.cell(0, i), h, font_size=Pt(9))

    # Data rows
    for r_idx, row in enumerate(cl_rows):
        for c_idx, val in enumerate(row):
            cell = cl_table.cell(r_idx + 1, c_idx)
            if c_idx == 0:
                # P0 Ticket column — clickable Jira hyperlink
                add_hyperlink_cell(slide, cell, [val], font_size=Pt(8))
            else:
                format_cell(cell, val, font_size=Pt(8), bold=False, color=DARK_GRAY)
            # Alternating row fill
            if r_idx % 2 == 1:
                set_cell_fill(cell, LIGHT_GRAY_BG)
            else:
                set_cell_fill(cell, WHITE)
            set_cell_border(cell)

    # Footnote text box below the table
    footnote_top = cl_tbl_top + cl_tbl_height + Inches(0.25)
    fn_box = slide.shapes.add_textbox(Inches(0.5), footnote_top, Inches(12.0), Inches(0.4))
    fn_tf = fn_box.text_frame
    fn_p = fn_tf.paragraphs[0]
    fn_run = fn_p.add_run()
    fn_run.text = '19 of 23 P0 tickets have NO fix in any changelog yet -- still actively being worked or awaiting verification.'
    fn_run.font.size = Pt(10)
    fn_run.font.italic = True
    fn_run.font.color.rgb = DARK_GRAY

    # Save
    output_dir = os.path.dirname(os.path.abspath(__file__))
    output_path = os.path.join(output_dir, 'critical_issue_status_p0_2026-03-26.pptx')
    prs.save(output_path)
    print('Saved: %s' % output_path)
    return output_path


if __name__ == '__main__':
    create_presentation()
