##########
# Script: generate_critical_issue_slides.py
# Description: Generate PowerPoint slides for Critical Issue Status meeting
# Author: John Macdonald (generated by OpenCode)
##########
'''
Generates critical_issue_status_2026-03-26.pptx from the root-cause-clustered
bug data. Matches the existing slide template style (purple headers, white rows).

Usage:
    python generate_critical_issue_slides.py

Output:
    critical_issue_status_2026-03-26.pptx in the same directory as this script.
'''

import os
from pptx import Presentation
from pptx.util import Inches, Pt, Emu
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN, MSO_ANCHOR
from pptx.oxml.ns import qn

# --- Color constants matching the existing template ---
PURPLE_HEADER = RGBColor(0x7B, 0x2D, 0x8E)  # Purple from the screenshot
WHITE = RGBColor(0xFF, 0xFF, 0xFF)
BLACK = RGBColor(0x00, 0x00, 0x00)
DARK_GRAY = RGBColor(0x33, 0x33, 0x33)
LIGHT_GRAY_BG = RGBColor(0xF2, 0xF2, 0xF2)  # Alternating row shading
CORNELIS_BLUE = RGBColor(0x00, 0x3D, 0x6B)   # Cornelis brand navy

JIRA_BASE = 'https://cornelisnetworks.atlassian.net/browse/'

# --- Slide dimensions (widescreen 16:9) ---
SLIDE_WIDTH = Inches(13.333)
SLIDE_HEIGHT = Inches(7.5)


def set_cell_fill(cell, color):
    '''Set solid fill color on a table cell.'''
    tc = cell._tc
    tcPr = tc.get_or_add_tcPr()
    # Remove any existing fill
    for child in list(tcPr):
        if child.tag.endswith('}solidFill') or child.tag.endswith('}noFill'):
            tcPr.remove(child)
    solidFill = tcPr.makeelement(qn('a:solidFill'), {})
    srgbClr = solidFill.makeelement(qn('a:srgbClr'), {'val': '%02X%02X%02X' % (color[0], color[1], color[2])})
    solidFill.append(srgbClr)
    tcPr.append(solidFill)


def set_cell_border(cell, color=RGBColor(0xCC, 0xCC, 0xCC), width=Pt(0.5)):
    '''Set thin borders on a cell.'''
    tc = cell._tc
    tcPr = tc.get_or_add_tcPr()
    for edge in ['lnL', 'lnR', 'lnT', 'lnB']:
        ln = tcPr.makeelement(qn('a:%s' % edge), {'w': str(int(width))})
        solidFill = ln.makeelement(qn('a:solidFill'), {})
        srgbClr = solidFill.makeelement(qn('a:srgbClr'), {'val': '%02X%02X%02X' % (color[0], color[1], color[2])})
        solidFill.append(srgbClr)
        ln.append(solidFill)
        # Remove existing same-tag element
        for existing in list(tcPr):
            if existing.tag == ln.tag:
                tcPr.remove(existing)
        tcPr.append(ln)


def format_cell(cell, text, font_size=Pt(9), bold=False, color=DARK_GRAY, alignment=PP_ALIGN.LEFT):
    '''Set text content and formatting on a table cell.'''
    cell.text = ''
    tf = cell.text_frame
    tf.word_wrap = True
    tf.auto_size = None
    # Reduce margins for tighter layout
    tf.margin_left = Pt(3)
    tf.margin_right = Pt(3)
    tf.margin_top = Pt(2)
    tf.margin_bottom = Pt(2)
    cell.vertical_anchor = MSO_ANCHOR.TOP

    p = tf.paragraphs[0]
    p.alignment = alignment
    p.space_before = Pt(0)
    p.space_after = Pt(0)
    run = p.add_run()
    run.text = text
    run.font.size = font_size
    run.font.bold = bold
    run.font.color.rgb = color


def format_header_cell(cell, text, font_size=Pt(9)):
    '''Format a header cell with purple background and white bold text.'''
    set_cell_fill(cell, PURPLE_HEADER)
    format_cell(cell, text, font_size=font_size, bold=True, color=WHITE)


def add_hyperlink_cell(cell, items, font_size=Pt(8)):
    '''Add cell content with Jira ticket IDs as hyperlinks.
    items is a list of (ticket_id, display_text) tuples, or just strings.
    '''
    cell.text = ''
    tf = cell.text_frame
    tf.word_wrap = True
    tf.margin_left = Pt(3)
    tf.margin_right = Pt(3)
    tf.margin_top = Pt(2)
    tf.margin_bottom = Pt(2)
    cell.vertical_anchor = MSO_ANCHOR.TOP

    p = tf.paragraphs[0]
    p.space_before = Pt(0)
    p.space_after = Pt(0)

    for i, item in enumerate(items):
        if i > 0:
            run = p.add_run()
            run.text = '\n'
            run.font.size = font_size

        if isinstance(item, tuple):
            ticket_id, display = item
            run = p.add_run()
            run.text = display
            run.font.size = font_size
            run.font.color.rgb = CORNELIS_BLUE
            run.font.underline = True
            # Add hyperlink via XML
            rPr = run._r.get_or_add_rPr()
            hlinkClick = rPr.makeelement(qn('a:hlinkClick'), {
                qn('r:id'): ''
            })
            rPr.append(hlinkClick)
            # Create relationship
            url = JIRA_BASE + ticket_id
            part = cell._tc.getparent().getparent().getparent().getparent()
            # We'll handle hyperlinks via the slide relationship
        else:
            run = p.add_run()
            run.text = item
            run.font.size = font_size
            run.font.color.rgb = DARK_GRAY


def add_table(slide, left, top, width, height, rows, cols):
    '''Add a table shape to a slide and return the table object.'''
    table_shape = slide.shapes.add_table(rows, cols, left, top, width, height)
    return table_shape.table


def add_title(slide, text, left=Inches(0.5), top=Inches(0.2), width=Inches(12), height=Inches(0.5)):
    '''Add a title text box to a slide.'''
    txBox = slide.shapes.add_textbox(left, top, width, height)
    tf = txBox.text_frame
    p = tf.paragraphs[0]
    run = p.add_run()
    run.text = text
    run.font.size = Pt(20)
    run.font.bold = True
    run.font.color.rgb = CORNELIS_BLUE
    return txBox


def add_subtitle(slide, text, left=Inches(0.5), top=Inches(0.65), width=Inches(12), height=Inches(0.35)):
    '''Add subtitle text below the title.'''
    txBox = slide.shapes.add_textbox(left, top, width, height)
    tf = txBox.text_frame
    p = tf.paragraphs[0]
    run = p.add_run()
    run.text = text
    run.font.size = Pt(11)
    run.font.color.rgb = DARK_GRAY
    return txBox


def build_rollup_table_data():
    '''Return (headers, rows) for the Slide 1 rollup table.'''
    headers = ['Area', 'Issues', 'Description', 'Customer', 'Status', 'Next Steps']
    rows = [
        [
            'BTS / Lustre',
            'STL-76950\nSTL-76880\nSTL-76940',
            'GPU DMA-buf deregistration race \u2014 mi300x kernel panics in rdmavt + Lustre RDMA timeouts with BTS. All hit same BTS memory lifecycle path.',
            '\u2014',
            'In Review /\nIn Progress',
            '76950 fix in review (Child); depends on 1 sub-fix in Verify + 2 still Open. If all land \u2192 cascade-fixes cluster.'
        ],
        [
            'OPX \u2014 TID cache',
            'STL-76365\nSTL-73247',
            'OPX TID cache diverges from kernel TID table under high expected-receive rate. HPL + sph_exa hangs. Chronic \u2014 73247 open since 12.1.0.x.',
            '\u2014',
            'In Progress',
            'Architecturally complex fix spanning OPX user-space + hfi1 kernel. Cernohous + Erwin.'
        ],
        [
            'OPX \u2014 GPU AI',
            'STL-77071',
            'MPT-30B hang with aws-ofi dmabuf. May overlap BTS DMA-buf cluster. New this week.',
            'RWTH',
            'Open',
            'Espinoza assessing. Possible user config issue \u2014 engaging customer.'
        ],
        [
            'OPX \u2014 Perf',
            'STL-76240',
            'IMB Biband/Sendrecv perf drop starting at OPXS 12.1.0.0-62. Data path regression on AMD.',
            'AMD',
            'In Progress',
            'Simonson bisecting OPX builds to isolate regression commit.'
        ],
        [
            'OPX / Lustre',
            'STL-77023',
            'Endeavour Lustre problems with use_bulksvc=N \u2014 fails even without BTS. New this week.',
            'Intel',
            'Open',
            'Child assessing. Waiting on dmesg from Intel.'
        ],
        [
            'Fabric / MYR FW',
            'STL-76338\nSTL-76494\nSTL-76725\nSTL-75962',
            'MYR switch buffer/credit mgmt \u2014 tportPktDropPending, RbufCtrlSbe, TxHoqDiscards, credit exhaustion. All related switch-side failures.',
            'TACC',
            'In Progress',
            'Wright on ISL drops. Rothermel on RbufCtrlSbe. King on HoQ discards. No fixes landed yet.'
        ],
        [
            'Fabric / MYR FW',
            'STL-77092',
            'DWC switch VR fault on liquid-cooled switch. HW issue, separate from buffer/credit. New this week.',
            'Lenovo',
            'In Review',
            'Nagarajan fix in review.'
        ],
        [
            'Host Driver \u2014\nIPoIB',
            'STL-76836\nSTL-74848',
            'ipoib timeout + SDMA Tx queue stalls. 74848 has sw_fixed. 76836 may be fabric-caused (links to 76494 + 76873).',
            'LLNL (Lynx)',
            'Open /\nIn Progress',
            'Test 74848 SDMA fix first. If unresolved, root cause is likely fabric-side.'
        ],
        [
            'Host Driver \u2014\nPCIe',
            'STL-75661\nSTL-76323\nSTL-76997',
            'Cards failing init after power events + runtime PCIe fatal errors under SPEC. All PCIe / 8051 FW path.',
            'Lenovo,\nIOCB,\nNEC/RWTH',
            'Open /\nIn Progress',
            'Davis on IOCB. Luick on SPEC crash. 75661 needs pickup (Zhang, Open).'
        ],
        [
            'Link / 8051 FW',
            'STL-76873',
            'Link fails LNI during EstablishComm.TxRxHunt \u2014 8051 FW SerDes link training failure. ~8 links affected.',
            'LLNL (Lynx)',
            'In Progress',
            'Johanson leading via Link Working Group.'
        ],
        [
            'Chassis',
            'STL-77046',
            'BMC FruDevice introspect fail \u2014 switch buggy state after bounce+reboot testing. Not data-path. New this week.',
            '\u2014',
            'Ready',
            'Queued for Nagarajan.'
        ],
    ]
    return headers, rows


def build_detail_data():
    '''Return detail slide data as list of dicts.'''
    slides = []

    # --- BTS / Lustre ---
    slides.append({
        'title': 'BTS / Lustre \u2014 Detail',
        'subtitle': '3 active + 6 in Verify \u2014 BTS memory deregistration race is the core root cause',
        'sections': [
            {
                'label': 'Active (3 bugs)',
                'headers': ['Issue', 'Pri', 'Summary', 'Assignee', 'Status', 'Root Cause / Blockers', 'Next Steps'],
                'col_widths': [0.9, 0.5, 2.0, 0.8, 0.7, 3.2, 2.5],
                'rows': [
                    ['STL-76950', 'P0', 'mi300x crash on ctl-c BTS/dmabuf \u2014 bulksvc_user_info_destroy', 'Child', 'In Review',
                     'GPU DMA-buf deregistration race. Blocked by:\nSTL-76982 (DMS unregister, Verify)\nSTL-76983 (force-cancel trackers, Open)\nSTL-76984 (rvt/bulksvc race, Open)',
                     'Retest with next DST once all 3 blockers land.'],
                    ['STL-76880', 'P0', 'mi300x GPU kernel panic rvt_send_complete', 'Simonson', 'In Progress',
                     'Same rdmavt DMA-buf path as 76950.',
                     'Likely fixed by 76950 patches. Retest together.'],
                    ['STL-76940', 'P0', 'LNetError RDMA timeout with BTS \u2014 Lustre client eviction', 'Simonson', 'In Progress',
                     'Lustre ko2iblnd hits BTS verbs path.\nCaused by STL-76941 (Verify).\nBlocked by STL-76999 (Verify).',
                     'Zhu: "Wait for 12.1.2 DST \u2014 fixed a few bugs."'],
                ],
            },
            {
                'label': 'Verify Queue (6 BTS fixes awaiting validation)',
                'headers': ['Issue', 'Summary', 'What It Fixes'],
                'col_widths': [1.2, 5.0, 4.4],
                'rows': [
                    ['STL-76982', 'Rearchitect DMS unregister to be always-async', 'Blocks 76950 (DMA-buf crash)'],
                    ['STL-76999', 'Fix bulksvc_dbg_open unbounded spin-wait deadlock', 'Blocks 76940 (Lustre RDMA timeout)'],
                    ['STL-76941', 'hfi1_dms_handle_data crash', 'Causes 76940 (Lustre RDMA timeout)'],
                    ['STL-76863', 'BAD WRITE CHECKSUM \u2014 BTS MR registration error', 'BTS Lustre data integrity'],
                    ['STL-76847', 'calculate_mr_page_offset Invalid', 'BTS Lustre data integrity'],
                    ['STL-76942', 'bufcount error \u2014 BTS buffer management', 'BTS Lustre data integrity'],
                    ['STL-76732', 'hfi1_dms_impl_dlist_remove crash \u2014 DMS list corruption', 'BTS internal locking'],
                ],
            },
        ],
    })

    # --- OPX ---
    slides.append({
        'title': 'OPX \u2014 Detail',
        'subtitle': '5 active + 2 in Verify \u2014 TID cache is chronic; perf regression + 2 new bugs this week',
        'sections': [
            {
                'label': 'Active (5 bugs)',
                'headers': ['Issue', 'Pri', 'Summary', 'Assignee', 'Status', 'Customer', 'Root Cause', 'Next Steps'],
                'col_widths': [0.9, 0.4, 1.8, 0.7, 0.6, 0.6, 2.5, 2.2],
                'rows': [
                    ['STL-76365', 'P0', 'HPL hang in hfi1_user_exp_rcv_setup', 'Cernohous', 'In Prog', '\u2014',
                     'OPX TID cache diverges from kernel. Links to 76561, 76972, 76685, 76554.',
                     'Fix spans OPX user-space + hfi1 kernel.'],
                    ['STL-73247', 'P0', 'sph_exa hang with OPX Open MPI', 'Erwin', 'In Prog', '\u2014',
                     'Same TID cache root cause. Open since 12.1.0.x.',
                     'Same fix as 76365.'],
                    ['STL-77071', 'P0', 'MPT-30B hang aws-ofi dmabuf', 'Espinoza', 'Open', 'RWTH',
                     'Possibly OPX+DMA-buf. May be user config.',
                     'Engaging RWTH directly.'],
                    ['STL-76240', 'P1', 'IMB Biband/Sendrecv perf drop', 'Simonson', 'In Prog', 'AMD',
                     'OPX data path regression in 12.1.0.0-62+. Blocks 76449, 77018, 76861.',
                     'Bisecting OPX builds.'],
                    ['STL-77023', 'P1', 'Endeavour Lustre use_bulksvc=N', 'Child', 'Open', 'Intel',
                     'Lustre fails without BTS. Separate root cause.',
                     'Waiting on dmesg from Intel.'],
                ],
            },
            {
                'label': 'Verify Queue (2 OPX fixes)',
                'headers': ['Issue', 'Summary', 'What It Fixes'],
                'col_widths': [1.2, 5.0, 4.4],
                'rows': [
                    ['STL-76561', 'HPL OPX_TID_CACHE assert with use_bulksvc:N', 'Related to TID cache cluster (76365, 73247)'],
                    ['STL-76644', 'NEC IMB-RMA SDMA abort \u2014 OPX rendezvous path', 'OPX data path correctness'],
                ],
            },
        ],
    })

    # --- Fabric / MYR FW ---
    slides.append({
        'title': 'Fabric / MYR FW \u2014 Detail',
        'subtitle': '5 active \u2014 Buffer/credit cluster is riskiest area (4 bugs, zero fixes landed)',
        'sections': [
            {
                'label': 'Active (5 bugs)',
                'headers': ['Issue', 'Pri', 'Summary', 'Assignee', 'Status', 'Customer', 'Root Cause', 'Next Steps'],
                'col_widths': [0.9, 0.4, 1.8, 0.7, 0.6, 0.5, 2.5, 2.3],
                'rows': [
                    ['STL-76338', 'P0', 'tportPktDropPending hang on ISL bounce', 'Wright', 'In Prog', 'TACC',
                     'MYR Tport state machine. Links to 76651, 76652, ISS-8041.',
                     'Reproduced internally. Wright analyzing.'],
                    ['STL-76494', 'P0', 'Hung nodes \u2014 RbufCtrlSbe ECC errors', 'Rothermel', 'In Prog', 'TACC',
                     'SRAM bit errors corrupt buffer mgmt. sw_fixed label. Links to 76836, 77090.',
                     'SW workaround exists. Watch SBE rate for HW degradation.'],
                    ['STL-76725', 'P1', 'Excessive TxHoqDiscards', 'King', 'In Prog', 'TACC',
                     'Head-of-queue blocking, same credit subsystem. Links to 75822.',
                     'Reproduced with synthetic ISL saturation.'],
                    ['STL-75962', 'P1', 'Job hang \u2014 MYR Tport credit exhaustion', 'Rothermel', 'In Prog', '\u2014',
                     'Transport credit accounting. Links to 75847.',
                     'Credit accounting analysis in progress.'],
                    ['STL-77092', 'P0', 'DWC switch VR fault (liquid-cooled)', 'Nagarajan', 'In Review', 'Lenovo',
                     'Voltage regulator HW fault. Separate from buffer/credit.',
                     'Fix in review.'],
                ],
            },
        ],
    })

    # --- Host Driver ---
    slides.append({
        'title': 'Host Driver \u2014 Detail',
        'subtitle': '5 active + 2 in Verify \u2014 76836 (LLNL ipoib) may be fabric-caused, not host driver',
        'sections': [
            {
                'label': 'Active (5 bugs)',
                'headers': ['Issue', 'Pri', 'Summary', 'Assignee', 'Status', 'Customer', 'Root Cause', 'Next Steps'],
                'col_widths': [0.9, 0.4, 1.6, 0.7, 0.6, 0.7, 2.6, 2.2],
                'rows': [
                    ['STL-76836', 'P0', 'ipoib timeout at LLNL Lynx', 'Novak', 'Open', 'LLNL',
                     'IPoIB/SDMA path. BUT: links to 76494 (RbufCtrlSbe) + 76873 (link training). May be fabric-caused.',
                     'Test 74848 SDMA fix first. If no fix, reclassify as fabric.'],
                    ['STL-74848', 'P1', 'SDMA Tx queue timeout \u2014 no descriptors', 'Hwang', 'In Prog', '\u2014',
                     'SDMA descriptor exhaustion. sw_fixed label.',
                     'Fix ready. Retest in next DST.'],
                    ['STL-76997', 'P0', 'Job crashes during SPEC run', 'Luick', 'Open', 'NEC/RWTH',
                     'Relates to 75193 (PCIe fatal error). Investigating uncorrectable error correlation.',
                     'Koch providing lspci. Luick proceeding with investigation.'],
                    ['STL-75661', 'P1', 'Link not Active after power-cycle', 'Zhang', 'Open', 'Lenovo',
                     '8051 FW / JKR FW PCIe init. Card fails to enumerate.',
                     'NEEDS PICKUP \u2014 Open, no recent activity.'],
                    ['STL-76323', 'P1', 'PCIe enumeration / HFI init failures', 'Davis', 'In Prog', 'IOCB',
                     'Same PCIe init path as 75661. 5/204 jobs failing.',
                     'Davis actively investigating. Repro rate reduced.'],
                ],
            },
            {
                'label': 'Verify Queue (2 Host Driver fixes)',
                'headers': ['Issue', 'Summary', 'What It Fixes'],
                'col_widths': [1.2, 5.0, 4.4],
                'rows': [
                    ['STL-77078', 'Nightly CI IB Verbs Atomic BW failure', 'CI regression'],
                    ['STL-76108', 'SRIOV VMs cannot query SA \u2014 sw_fixed', 'SRIOV connectivity'],
                ],
            },
        ],
    })

    # --- Link / 8051 FW + Chassis ---
    slides.append({
        'title': 'Link / 8051 FW + Chassis \u2014 Detail',
        'subtitle': '2 active \u2014 Link training at LLNL + BMC management issue',
        'sections': [
            {
                'label': 'Active (2 bugs)',
                'headers': ['Issue', 'Pri', 'Summary', 'Assignee', 'Status', 'Customer', 'Root Cause', 'Next Steps'],
                'col_widths': [0.9, 0.4, 2.0, 0.8, 0.6, 0.7, 2.5, 2.3],
                'rows': [
                    ['STL-76873', 'P0', 'Link fails LNI during EstablishComm.TxRxHunt', 'Johanson', 'In Prog', 'LLNL',
                     '8051 FW SerDes link training. ~8 links not coming up. Links to 76836 (ipoib).',
                     'Johanson leading via Link Working Group.'],
                    ['STL-77046', 'P1', 'BMC FruDevice introspect fail \u2014 buggy state', 'Nagarajan', 'Ready', '\u2014',
                     'Chassis mgmt. After ~17h link bounce + reboot test. Not data-path.',
                     'Queued for Nagarajan.'],
                ],
            },
        ],
    })

    return slides


def create_presentation():
    '''Build the full PowerPoint presentation.'''
    prs = Presentation()
    # Set 16:9 widescreen
    prs.slide_width = SLIDE_WIDTH
    prs.slide_height = SLIDE_HEIGHT

    # Use blank layout
    blank_layout = prs.slide_layouts[6]  # Blank

    # ===== SLIDE 1: Scoreboard + Rollup =====
    slide = prs.slides.add_slide(blank_layout)
    add_title(slide, 'Critical Issue Status \u2014 2026-03-26')
    add_subtitle(slide, 'Source: Jira filter "SW 12.1.2 Targeted P0/P1 Bugs" (33573)  |  33 bugs: 23 P0, 10 P1  |  20 active, 9 Verify, 4 Closed')

    # Scoreboard row
    sb_left = Inches(0.5)
    sb_top = Inches(1.05)
    sb_width = Inches(10.0)
    sb_height = Inches(0.55)
    sb_table = add_table(slide, sb_left, sb_top, sb_width, sb_height, 2, 4)

    sb_headers = ['Open Critical', 'New This Week', 'Waiting for Verify in DST', 'Actively Root-Causing']
    sb_values = ['20', '5', '9', '12']
    for i, (h, v) in enumerate(zip(sb_headers, sb_values)):
        sb_table.columns[i].width = Inches(2.5)
        format_header_cell(sb_table.cell(0, i), h, font_size=Pt(10))
        sb_table.cell(0, i).text_frame.paragraphs[0].alignment = PP_ALIGN.CENTER
        format_cell(sb_table.cell(1, i), v, font_size=Pt(18), bold=True, color=CORNELIS_BLUE, alignment=PP_ALIGN.CENTER)
        set_cell_fill(sb_table.cell(1, i), WHITE)

    # Rollup table
    headers, rows = build_rollup_table_data()
    n_rows = len(rows) + 1  # +1 for header
    n_cols = len(headers)
    tbl_left = Inches(0.3)
    tbl_top = Inches(1.75)
    tbl_width = Inches(12.7)
    tbl_height = Inches(5.5)

    table = add_table(slide, tbl_left, tbl_top, tbl_width, tbl_height, n_rows, n_cols)

    # Column widths: Area, Issues, Description, Customer, Status, Next Steps
    col_widths = [1.1, 1.0, 3.8, 0.9, 0.9, 5.0]
    for i, w in enumerate(col_widths):
        table.columns[i].width = Inches(w)

    # Header row
    for i, h in enumerate(headers):
        format_header_cell(table.cell(0, i), h, font_size=Pt(9))

    # Data rows
    for r_idx, row in enumerate(rows):
        for c_idx, val in enumerate(row):
            cell = table.cell(r_idx + 1, c_idx)
            is_bold = (c_idx == 0)  # Bold the area column
            font_size = Pt(8) if c_idx in (2, 5) else Pt(8)
            format_cell(cell, val, font_size=font_size, bold=is_bold, color=DARK_GRAY)
            # Alternate row shading
            if r_idx % 2 == 1:
                set_cell_fill(cell, LIGHT_GRAY_BG)
            else:
                set_cell_fill(cell, WHITE)
            set_cell_border(cell)

    # ===== DETAIL SLIDES =====
    detail_slides = build_detail_data()

    for detail in detail_slides:
        slide = prs.slides.add_slide(blank_layout)
        add_title(slide, detail['title'])
        add_subtitle(slide, detail['subtitle'])

        current_top = Inches(1.1)

        for section in detail['sections']:
            # Section label
            label_box = slide.shapes.add_textbox(Inches(0.5), current_top, Inches(8), Inches(0.3))
            tf = label_box.text_frame
            p = tf.paragraphs[0]
            run = p.add_run()
            run.text = section['label']
            run.font.size = Pt(11)
            run.font.bold = True
            run.font.color.rgb = DARK_GRAY
            current_top += Inches(0.35)

            headers = section['headers']
            rows = section['rows']
            col_widths = section['col_widths']
            n_rows = len(rows) + 1
            n_cols = len(headers)

            # Calculate total width from col_widths
            total_w = sum(col_widths)
            # Scale to fit 12.3 inches
            scale = 12.3 / total_w
            scaled_widths = [w * scale for w in col_widths]

            # Estimate row height: ~0.35 per row for detail tables
            row_h = 0.35
            tbl_height = Inches(min((n_rows * row_h), 4.0))

            table = add_table(slide, Inches(0.5), current_top, Inches(12.3), tbl_height, n_rows, n_cols)

            for i, w in enumerate(scaled_widths):
                table.columns[i].width = Inches(w)

            # Header
            for i, h in enumerate(headers):
                format_header_cell(table.cell(0, i), h, font_size=Pt(8))

            # Data
            for r_idx, row in enumerate(rows):
                for c_idx, val in enumerate(row):
                    cell = table.cell(r_idx + 1, c_idx)
                    # First column (Issue) gets special treatment for ticket IDs
                    is_bold = False
                    font_sz = Pt(8)
                    format_cell(cell, val, font_size=font_sz, bold=is_bold, color=DARK_GRAY)
                    if r_idx % 2 == 1:
                        set_cell_fill(cell, LIGHT_GRAY_BG)
                    else:
                        set_cell_fill(cell, WHITE)
                    set_cell_border(cell)

                    # Add hyperlink for Issue column (first column with STL- prefix)
                    if c_idx == 0 and val.startswith('STL-'):
                        # Make it look like a link
                        cell.text_frame.paragraphs[0].runs[0].font.color.rgb = CORNELIS_BLUE
                        cell.text_frame.paragraphs[0].runs[0].font.underline = True
                        # Add actual hyperlink
                        run_elem = cell.text_frame.paragraphs[0].runs[0]._r
                        rPr = run_elem.get_or_add_rPr()
                        hlinkClick = rPr.makeelement(qn('a:hlinkClick'), {})
                        url = JIRA_BASE + val
                        rel = slide.part.relate_to(url, 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/hyperlink', is_external=True)
                        hlinkClick.set(qn('r:id'), rel)
                        rPr.append(hlinkClick)

            current_top += tbl_height + Inches(0.2)

    # ===== SLIDE 7: Root Cause Cluster Summary =====
    slide = prs.slides.add_slide(blank_layout)
    add_title(slide, 'Root Cause Cluster Summary')
    add_subtitle(slide, '20 active bugs \u2192 7 root causes + 5 standalone')

    rc_headers = ['#', 'Root Cause', 'Active', 'Verify', 'Closed', 'Fix One, Fix All?']
    rc_rows = [
        ['1', 'BTS DMA-buf deregistration race', '3', '6', '1', 'Yes \u2014 76950 fix in review \u2192 cascade-fixes. But 2 of 3 blockers still Open.'],
        ['2', 'OPX TID cache kernel divergence', '2', '1', '\u2014', 'Yes \u2014 same arch fix. Complex (user + kernel).'],
        ['3', 'MYR buffer/credit switch FW', '4', '\u2014', '\u2014', 'Partially \u2014 related but may need separate fixes. Zero resolved.'],
        ['4', 'IPoIB / SDMA transmit', '2', '\u2014', '\u2014', 'Maybe \u2014 74848 sw_fixed may resolve 76836.'],
        ['5', 'PCIe / card init', '3', '\u2014', '\u2014', 'Partially \u2014 75661 + 76323 same path, 76997 is runtime.'],
        ['6', 'OPX GPU AI', '1', '\u2014', '2', 'TBD \u2014 77071 may be user config.'],
        ['7', 'OPX perf regression', '1', '1', '1', 'Separate \u2014 bisecting to isolate commit.'],
        ['8', 'Link training 8051 FW', '1', '\u2014', '\u2014', 'Standalone. Link WG owns.'],
        ['\u2014', 'Standalone (Lustre non-BTS, VR, BMC, CI, SRIOV)', '4', '2', '\u2014', 'Each separate.'],
    ]

    n_rows = len(rc_rows) + 1
    n_cols = len(rc_headers)
    table = add_table(slide, Inches(0.5), Inches(1.1), Inches(12.3), Inches(4.0), n_rows, n_cols)

    rc_col_widths = [0.3, 2.5, 0.6, 0.6, 0.6, 7.7]
    for i, w in enumerate(rc_col_widths):
        table.columns[i].width = Inches(w)

    for i, h in enumerate(rc_headers):
        format_header_cell(table.cell(0, i), h, font_size=Pt(9))

    for r_idx, row in enumerate(rc_rows):
        for c_idx, val in enumerate(row):
            cell = table.cell(r_idx + 1, c_idx)
            bold = (c_idx == 1)
            align = PP_ALIGN.CENTER if c_idx in (0, 2, 3, 4) else PP_ALIGN.LEFT
            format_cell(cell, val, font_size=Pt(9), bold=bold, color=DARK_GRAY, alignment=align)
            if r_idx % 2 == 1:
                set_cell_fill(cell, LIGHT_GRAY_BG)
            else:
                set_cell_fill(cell, WHITE)
            set_cell_border(cell)

    # Key Callouts box
    callout_top = Inches(5.3)
    callout_box = slide.shapes.add_textbox(Inches(0.5), callout_top, Inches(12.3), Inches(2.0))
    tf = callout_box.text_frame
    tf.word_wrap = True

    callouts = [
        'BTS is #1 area \u2014 3 active + 6 in Verify. 76950 fix depends on 2 patches still Open (76983, 76984). Next DST is the gate.',
        'MYR buffer/credit is riskiest \u2014 4 bugs, all In Progress, zero fixes landed. TACC is primary customer.',
        '76836 (LLNL ipoib) may be fabric-caused \u2014 test SDMA fix first; if no resolution, reclassify.',
        'OPX TID hangs still chronic \u2014 73247 open since 12.1.0.x. Architecturally complex fix.',
        '75661 (Lenovo power-cycle) needs pickup \u2014 assigned to Zhang, Open, no recent activity.',
    ]

    for i, text in enumerate(callouts):
        if i == 0:
            p = tf.paragraphs[0]
        else:
            p = tf.add_paragraph()
        p.space_before = Pt(2)
        p.space_after = Pt(2)
        # Bullet number
        run = p.add_run()
        run.text = '%d. %s' % (i + 1, text)
        run.font.size = Pt(9)
        run.font.color.rgb = DARK_GRAY

    # Save
    output_dir = os.path.dirname(os.path.abspath(__file__))
    output_path = os.path.join(output_dir, 'critical_issue_status_2026-03-26.pptx')
    prs.save(output_path)
    print('Saved: %s' % output_path)
    return output_path


if __name__ == '__main__':
    create_presentation()
